[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/workshop"
  to = "/workshop/"
  status = 301

[[redirects]]
  from = "/storedash"
  to = "/storedash/"
  status = 301

[[redirects]]
  from = "/reviews"
  to = "/reviews/"
  status = 301

[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/reviews/*"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[headers]]
  for = "/reviews/index.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

[[redirects]]
  from = "/inventory"
  to = "/inventory/"
  status = 301
