[build]
  command = "npm install"
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/workshop"
  to = "/workshop/"
  status = 301

[[redirects]]
  from = "/storedash"
  to = "/storedash/"
  status = 301
